// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynarqggeklshaabnhcjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluYXJxZ2dla2xzaGFhYm5oY2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMTc3MDIsImV4cCI6MjA3MTU5MzcwMn0.mfh1tdvhxEYEEO977RcS9nHvYVFMVC2ndEK7_paURFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});